services:
  - type: web
    name: location-share
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python3 server/app.py
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE
        value: locations.db
    disk:
      mountPath: /opt/render/project/src
      name: location-share-data
      sizeGB: 1